# Generated by Django 3.0 on 2021-01-24 18:12

from django.db import migrations, models


def set_my_defaults(apps, schema_editor):
    Ad = apps.get_model('main', 'Ad')
    for ad in Ad.objects.all():
        ad.title = str(ad.description)
        ad.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(default='default_title', max_length=120),
            preserve_default=False,
        ),
        migrations.RunPython(set_my_defaults, reverse_func)
    ]