# Generated by Django 3.0 on 2021-02-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('not_active', 'Модерируется'), ('archive', 'Архив')], default='not_active', max_length=20),
        ),
    ]
