# Generated by Django 3.0 on 2021-01-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ad_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='title',
        ),
    ]
