# Generated by Django 3.0 on 2021-03-01 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default='{}', size=None),
            preserve_default=False,
        ),
    ]
