# Generated by Django 3.0 on 2021-03-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ad_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='tags',
            new_name='custom_tags',
        ),
    ]
