version: '3.8'

services:
  web:
    build: ./
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/rental_site
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    hostname: db
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_user
      - POSTGRES_DB=django_db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A rental_site worker -l info
    volumes:
      - ./:/rental_site
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
volumes:
  postgres_data: